/*global define, describe, it, expect*/

//Each new term in the Fibonacci sequence is generated by adding the previous two terms.
// By starting with 1 and 2, the first 10 terms will be:
//1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
//By considering the terms in the Fibonacci sequence whose values do not exceed four million,
//find the sum of the even-valued terms.

define(['problem2'], function(problem2) {
    "use strict";

    describe('problem2: Even Fibonacci numbers -', function() {

        it('should sum even value fibonacci numbers under 10', function() {
            var result = problem2(10);
            expect(result).toEqual(10);
        });

        it('should sum even value fibonacci numbers under 34', function() {
            var result = problem2(34);
            expect(result).toEqual(44);
        });

        it('should sum even value fibonacci numbers under 4,000,000', function() {
            var result = problem2(4000000);
            expect(result).toEqual(4613732);
        });

    });

});
