/*global define*/

//Each new term in the Fibonacci sequence is generated by adding the previous two terms.
// By starting with 1 and 2, the first 10 terms will be:
//1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
//By considering the terms in the Fibonacci sequence whose values do not exceed four million,
//find the sum of the even-valued terms.
define(function () {
    "use strict";

    var problem2 = function (upperBound) {
        var sum = 2,
            fibonacci = [],
            nextSequence;

        fibonacci.push(1);
        fibonacci.push(2);

        nextSequence = fibonacci[fibonacci.length-2] + fibonacci[fibonacci.length-1];

        while (nextSequence < upperBound) {
            fibonacci.push(nextSequence);
            if (nextSequence % 2 === 0) {
                sum += nextSequence;
            }
            nextSequence = fibonacci[fibonacci.length-2] + fibonacci[fibonacci.length-1];
        }

        return sum;
    };

    return problem2;

});
